apiVersion: v2
name: cloudscan
description: CloudScan - Open Source Security & Quality Scanning Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - security
  - sast
  - sca
  - scanning
  - devsecops
home: https://github.com/cloudscan/cloudscan
sources:
  - https://github.com/cloudscan/cloudscan
maintainers:
  - name: CloudScan Team
    email: team@cloudscan.dev
dependencies:
  - name: postgresql
    version: "18.2.3"
    repository: https://charts.bitnami.com/bitnami
    condition: onPrem.postgresql
  - name: redis
    version: "24.1.2"
    repository: https://charts.bitnami.com/bitnami
    condition: onPrem.redis
  - name: minio
    version: "17.0.21"
    repository: https://charts.bitnami.com/bitnami
    condition: onPrem.minio