
orchestrator:
  image:
    tag: "2026.02.30-main"

apiGateway:
  image:
    tag: "2026.02.13-main"

storage:
  image:
    tag: "2026.02.18-main"

websocket:
  image:
    tag: "2025.10.2-main"

ui:
  image:
    tag: "2026.02.13-main"

runner:
  image:
    tag: "2026.02.4-main"
