{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudscan-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
{{- end }}
