{{- if .Values.storage.enabled }}
{{- $_ := set . "serviceName" "storage" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudscan.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.storage.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.storage.service.httpPort | default .Values.storage.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "cloudscan.service.selectorLabels" . | nindent 4 }}
{{- end }}